sudo: required
dist: xenial
language: cpp

cache:
  - apt
  - directories:

compiler:
  - g++

os:
  - unix

addons:
  ssh_known_hosts:
    - github.com

env:
  global:
    - SOURCE_DIR=$TRAVIS_BUILD_DIR
    - RABBITIM_USE_REPOSITORIES="TRUE"
    - QMAKE=qmake

  matrix:
    - BUILD_TARGERT="unix" QT_VERSION_DIR=512 QT_VERSION=5.12.3 BUILD_DOWNLOAD=FALSE
    - BUILD_TARGERT="unix" QT_VERSION_DIR=511 QT_VERSION=5.11.3 BUILD_DOWNLOAD=FALSE
    - BUILD_TARGERT="unix" QT_VERSION_DIR=511 QT_VERSION=5.11.3 BUILD_DOWNLOAD=FALSE GENERATORS="Unix Makefiles"

    - BUILD_TARGERT="unix" BUILD_ARCH="unix" QT_VERSION_DIR=5.12 QT_VERSION=5.12.4 BUILD_DOWNLOAD=TRUE GENERATORS="Unix Makefiles"
    - BUILD_TARGERT="unix" BUILD_ARCH="unix" QT_VERSION_DIR=5.13 QT_VERSION=5.13.2 BUILD_DOWNLOAD=TRUE STATIC=ON

    - BUILD_TARGERT="android" BUILD_ARCH="armeabi-v7a" ANDROID_ARM_NEON=ON QT_VERSION_DIR=5.13 QT_VERSION=5.13.2 ANDROID_API=android-24 BUILD_DOWNLOAD=TRUE
    - BUILD_TARGERT="android" BUILD_ARCH="armeabi-v7a" ANDROID_ARM_NEON=ON QT_VERSION_DIR=5.12 QT_VERSION=5.12.4 ANDROID_API=android-24 BUILD_DOWNLOAD=TRUE GENERATORS="Unix Makefiles"
    - BUILD_TARGERT="android" BUILD_ARCH="x86" QT_VERSION_DIR=5.12 QT_VERSION=5.12.5 ANDROID_API=android-24 BUILD_DOWNLOAD=TRUE STATIC=ON

before_install:
  - echo "TRAVIS_OS_NAME=${TRAVIS_OS_NAME}"
  - sudo apt-get install -y -qq xvfb xpra
  - sudo Xvfb :99 -ac &
  - export DISPLAY=:99.0
  - mkdir ${SOURCE_DIR}/Tools
  - export VERSION="v1.0.0"

install:
  - bash ci/build-install-tools.sh > /dev/null

before_script:
  - cd ${SOURCE_DIR}

script: 
  - bash ${SOURCE_DIR}/ci/build.sh ${SOURCE_DIR}

notifications:
  email: kl222@126.com
  on_success: never  # [always|never|change]
  on_failure: always

#deploy:
#  provider: releases
#  api_key: 177ce637a8ec54e66ea8693092caf35059cf95d7
#  file: 
#    - ./build_android/android-build/bin/QtApp-debug.apk
#  skip_cleanup: true
#  on:
#    condition: $TRAVIS_OS_NAME = android
#    repo: KangLin/RabbitCommon
#    tags: true
