#TODO: Change version
version: 'v1.0.13.{build}'

environment:
  matrix:
  ##### msvc 2019 ########
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    VC_DIR: 2019
    GENERATORS: "Visual Studio 16 2019"
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 16
    QT_ROOT: C:\Qt\6.2\msvc2019_64
    BUILD_ARCH: x64
    STATIC: ON
    
  ##### msvc 2013 ########
  - BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 12
    QT_ROOT: C:\Qt\5.6\msvc2013
    BUILD_ARCH: x86
    
  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 12 2013"
    TOOLCHAIN_VERSION: 12
    QT_ROOT: C:\Qt\5.6\msvc2013
    BUILD_ARCH: x86
  
  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 12 2013 Win64"
    TOOLCHAIN_VERSION: 12
    QT_ROOT: C:\Qt\5.6\msvc2013_64
    BUILD_ARCH: x64

  ##### msvc 2015 ########
  - BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 14
    QT_ROOT: C:\Qt\5.10\msvc2015
    BUILD_ARCH: x86
    
  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 14 2015"
    TOOLCHAIN_VERSION: 14
    QT_ROOT: C:\Qt\5.10\msvc2015
    BUILD_ARCH: x86

  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 14 2015 Win64"
    TOOLCHAIN_VERSION: 14
    QT_ROOT: C:\Qt\5.10\msvc2015_64
    BUILD_ARCH: x64
  
  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 14 2015"
    TOOLCHAIN_VERSION: 14
    QT_ROOT: C:\Qt\5.6\msvc2015
    BUILD_ARCH: x86

  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 14 2015 Win64"
    TOOLCHAIN_VERSION: 14
    QT_ROOT: C:\Qt\5.6\msvc2015_64
    BUILD_ARCH: x64

  ##### msvc 2017 ########
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    BUILD_TARGERT: windows_msvc
    VC_DIR: 2017
    TOOLCHAIN_VERSION: 15
    QT_ROOT: C:\Qt\5.12\msvc2017
    BUILD_ARCH: x86
    STATIC: ON
    
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    GENERATORS: "Visual Studio 15 2017"
    VC_DIR: 2017
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 15
    QT_ROOT: C:\Qt\5.12\msvc2017
    BUILD_ARCH: x86
    STATIC: ON

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    GENERATORS: "Visual Studio 15 2017 Win64"
    VC_DIR: 2017
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 15
    QT_ROOT: C:\Qt\5.12\msvc2017_64
    BUILD_ARCH: x64
    STATIC: ON
    
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    VC_DIR: 2017
    GENERATORS: "Visual Studio 15 2017 Win64"
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 15
    QT_ROOT: C:\Qt\5.10\msvc2017_64
    BUILD_ARCH: x64
  
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    VC_DIR: 2017
    GENERATORS: "Visual Studio 15 2017 Win64"
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 15
    QT_ROOT: C:\Qt\5.9\msvc2017_64
    BUILD_ARCH: x64
    
  ##### mingw ########
  - BUILD_TARGERT: windows_mingw
    GENERATORS: "MSYS Makefiles"
    TOOLCHAIN_VERSION: 492_32
    QT_ROOT: C:\Qt\5.6\mingw49_32
    BUILD_ARCH: x86

  - BUILD_TARGERT: windows_mingw
    TOOLCHAIN_VERSION: 530_32
    QT_ROOT: C:\Qt\5.10\mingw53_32
    BUILD_ARCH: x86
    
  - BUILD_TARGERT: windows_mingw
    TOOLCHAIN_VERSION: 730_64
    QT_ROOT: C:\Qt\5.12\mingw73_64
    BUILD_ARCH: x64
  
  ##### android ########
#  - BUILD_TARGERT: android
#    GENERATORS: "MSYS Makefiles"
#    BUILD_ARCH: "armeabi-v7a"
#    ANDROID_ARM_NEON: ON
#    QT_ROOT: NO
#    QT_VERSION_DIR: 5.12
#    QT_VERSION: 5.12.6
#    ANDROID_PLATFORM: android-24
#    TOOLCHAIN_VERSION: 4.9
    
matrix:
  fast_finish: false

init:
  - set RabbitCommon_VERSION=%APPVEYOR_VERSION%
  - set varch=%BUILD_ARCH%
  - if "%BUILD_ARCH%" == "x64" set varch=amd64
  - if "%BUILD_TARGERT%" == "windows_msvc" if %TOOLCHAIN_VERSION% LSS 15 (call "C:\Program Files (x86)\Microsoft Visual Studio %TOOLCHAIN_VERSION%.0\VC\vcvarsall.bat" %varch%) else (call "C:\Program Files (x86)\Microsoft Visual Studio\%VC_DIR%\Community\VC\Auxiliary\Build\vcvarsall.bat" %varch%)  
  - echo NUMBER_OF_PROCESSORS=%NUMBER_OF_PROCESSORS%
  - echo PROCESSOR_IDENTIFIER=%PROCESSOR_IDENTIFIER%
  - if NOT "%QT_ROOT%" == "NO" for /f "delims=" %%i in ('%QT_ROOT%/bin/qmake -query QT_VERSION') do (set QT_VERSION=%%i) 
  - echo QT_ROOT=%QT_ROOT%
  - echo QT_VERSION=%QT_VERSION%
  - del C:\msys64\usr\bin\link.exe
  
install:
  - C:\msys64\autorebase.bat
  - C:\msys64\usr\bin\pacman.exe -S --noconfirm unzip
  #- if "%BUILD_TARGERT%"=="windows_mingw" set PATH=C:\Qt\Tools\mingw%TOOLCHAIN_VERSION%_32\bin;%PATH%
  - if "%BUILD_TARGERT%" == "windows_mingw" set MSYSTEM=MINGW32  #设置编译系统为MINGW32

  - cd %APPVEYOR_BUILD_FOLDER%\Tools
  - set CMAKE_VERSION=3.25.0
  - if not exist cmake-%CMAKE_VERSION%-windows-i386 (curl -fsSL -o cmake-%CMAKE_VERSION%-windows-i386.zip https://github.com/Kitware/CMake/releases/download/v%CMAKE_VERSION%/cmake-%CMAKE_VERSION%-windows-i386.zip && 7z x cmake-%CMAKE_VERSION%-windows-i386.zip)
  - cd cmake-%CMAKE_VERSION%-windows-i386
  - set PATH="%CD%/bin";%PATH%

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  - if "%BUILD_TARGERT%" == "android" C:\msys64\usr\bin\bash.exe %APPVEYOR_BUILD_FOLDER%\ci\build-install-tools-windows.sh

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - C:\msys64\usr\bin\bash.exe %APPVEYOR_BUILD_FOLDER%\ci\build.sh

artifacts:
  - path: build_${BUILD_TARGERT}/install
    name: RabbitCommon_$(BUILD_TARGERT)$(TOOLCHAIN_VERSION)_$(GENERATORS)_$(BUILD_ARCH)_Qt$(QT_VERSION)_$(RabbitCommon_VERSION)
    type: zip

test: off

#See:https://www.appveyor.com/docs/deployment/github/
deploy:
  - provider: GitHub
    #release: RabbitCommon_$(RabbitCommon_VERSION)
    description: 'Release RabbitCommon $(APPVEYOR_REPO_TAG_NAME) on windows'
    #token : https://github.com/settings/tokens password encrypt: https://ci.appveyor.com/tools/encrypt
    auth_token:
      secure: +wHYWKg2S7ggmOYHDVuvI9EQEy0qOyQhbsBgIQ+Jyn6YpEsUsRhGfQlBl1bR06K1
    #artifact: RabbitCommon$(BUILD_TARGERT)$(TOOLCHAIN_VERSION)_$(BUILD_ARCH)_$(QT_VERSION)_$(RabbitCommon_VERSION)
    #draft: true
    #prerelease: true
    on:
      BUILD_TARGERT: windows_msvc
      appveyor_repo_tag: true        # deploy on tag push only
