name: rabbitcommon # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '2.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Rabbit Common library # 79 char long summary
description: |
  Rabbit common library

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  rabbitcommon:
    # See 'snapcraft plugins'
    source: . 
    plugin: cmake
    build-packages:
      - libcrypt-dev
      - libopengl-dev
      - libglu1-mesa-dev 
      - qt6-tools-dev
      - qt6-tools-dev-tools
      - qt6-base-dev
      - qt6-base-dev-tools
      - qt6-qpa-plugins
      - libqt6svg6-dev
      - qt6-l10n-tools
      - qt6-translations-l10n
      - qt6-scxml-dev
      - qt6-multimedia-dev
      - libqt6serialport6-dev
      - qt6-webengine-dev
      - qt6-webengine-dev-tools
    stage-packages:
      - libpulse-mainloop-glib0
