name: rabbitcommon # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
version: '2.0.6' # just for humans, typically '1.2+git' or '1.3.2'
summary: Rabbit Common library # 79 char long summary
description: |
  Rabbit common library

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  build:
    # See 'snapcraft plugins'
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
    source: .
    build-packages:
      - qt6-webengine-dev
      - qt6-webengine-dev-tools
      - libcrypt-dev
      - libopengl-dev
      - libglu1-mesa-dev 
      - qt6-tools-dev
      - qt6-tools-dev-tools
      - qt6-base-dev
      - qt6-base-dev-tools
      - qt6-qpa-plugins
      - libqt6svg6-dev
      - qt6-l10n-tools
      - qt6-translations-l10n
      - qt6-scxml-dev
      - qt6-webengine-dev
      - qt6-webengine-dev-tools
      - libpulse-mainloop-glib0
      - cmark
