# How Snapcraft builds snaps: https://snapcraft.io/docs/how-snapcraft-builds
# Snapcraft.yaml schema: https://snapcraft.io/docs/snapcraft-yaml-schema
name: rabbitcommon # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
version: '2.0.6' # just for humans, typically '1.2+git' or '1.3.2'
license: GPL-3.0+
contact: kl222@126.com
donation:
  - https://gitlab.com/kl222/RabbitCommon/-/raw/master/Src/Resource/image/Contribute.png
issues: https://github.com/KangLin/RabbitCommon/issues
summary: Rabbit Common library # 79 char long summary
description: |
  Rabbit common library

grade: devel # must be 'stable' to release into candidate/stable channels
# Confinement levels: https://snapcraft.io/docs/classic-confinement#heading--levels
# Classic confinement: https://snapcraft.io/docs/classic-confinement
confinement: devmode # use 'strict' once you have the right plugs and slots

# lifecycle: https://snapcraft.io/docs/parts-lifecycle
# Iterating over a build: https://snapcraft.io/docs/iterating-over-a-build
# Part directives: https://snapcraft.io/docs/snapcraft-yaml-schema#part-directives
parts:
  build:
    # see: https://snapcraft.io/docs/supported-plugins
    # See 'snapcraft plugins'
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
    source: .
    build-packages:
      - qt6-webengine-dev
      - qt6-webengine-dev-tools
      - libcrypt-dev
      - libopengl-dev
      - libglu1-mesa-dev 
      - qt6-tools-dev
      - qt6-tools-dev-tools
      - qt6-base-dev
      - qt6-base-dev-tools
      - qt6-qpa-plugins
      - libqt6svg6-dev
      - qt6-l10n-tools
      - qt6-translations-l10n
      - qt6-scxml-dev
      - qt6-webengine-dev
      - qt6-webengine-dev-tools
      - libpulse-mainloop-glib0
      - cmark
