# How Snapcraft builds snaps: https://snapcraft.io/docs/how-snapcraft-builds
# Snapcraft.yaml schema: https://snapcraft.io/docs/snapcraft-yaml-schema
name: rabbitcommon # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '2.3.4'
license: GPL-3.0+
contact: kl222@126.com
donation:
  - https://gitlab.com/kl222/RabbitCommon/-/raw/master/Src/Resource/image/Contribute.png
issues: https://github.com/KangLin/RabbitCommon/issues
summary: Rabbit Common library # 79 char long summary
description: |
  Rabbit common library

grade: devel # must be 'stable' to release into candidate/stable channels
# Confinement levels: https://snapcraft.io/docs/classic-confinement#heading--levels
# Classic confinement: https://snapcraft.io/docs/classic-confinement
confinement: devmode # use 'strict' once you have the right plugs and slots

# lifecycle: https://snapcraft.io/docs/parts-lifecycle
# Iterating over a build: https://snapcraft.io/docs/iterating-over-a-build
# Part directives: https://snapcraft.io/docs/snapcraft-yaml-schema#part-directives
parts:
  build:
    # see: https://snapcraft.io/docs/supported-plugins
    # See 'snapcraft plugins'
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_APP=OFF
      - -DBUILD_TESTS=OFF
    source: .
    build-packages:
      - qttools5-dev
      - qtbase5-dev
      - libqt5scxml5-dev
      - libqt5svg5-dev
      - cmark
      - libcmark-dev
      - libssl-dev
      - libcrypt-dev
      - libcurl4-openssl-dev
    stage-packages:
      - libcmark0.30.2
      - libssl3
      - libcrypt1
      - libqt5scxml5
      - libqt5svg5
      - libqt5xml5
      - libcurl4
    stage:
      - -usr/local/include
      - -usr/local/lib/cmake
      - -usr/local/lib/pkgconfig

# App directives: https://snapcraft.io/docs/snapcraft-yaml-schema#app-directives
apps:
 FileBrowser:
   command: usr/local/bin/FileBrowser
   environment:
     LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/local/lib
     PATH: $SNAP/usr/local/bin:$PATH
   # List extensions, run `snapcraft extensions`
   extensions:
     - kde-neon
   # See: https://snapcraft.io/docs/supported-interfaces
   plugs:
     - network
     - home
