name: build

env:
  artifact_path: artifact_path

on: 
  push:
  
jobs:
  build_ubuntu:
    uses: ./.github/workflows/ubuntu.yml

  build_msvc:
    uses: ./.github/workflows/msvc.yml

  build_mingw:
    uses: ./.github/workflows/mingw.yml

  deploy:
    runs-on: ubuntu-latest
    needs: [build_ubuntu, build_mingw, build_msvc]
    steps:
#      - name: Download ubuntu
#        uses: actions/download-artifact@v3
#        with:
#          name: ${{ needs.build_ubuntu.outputs.name }}
#          path: ${{ env.artifact_path }}

      - name: Download msvc
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build_msvc.outputs.name }}
          path: ${{ env.artifact_path }}

      - name: Download mingw
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build_mingw.outputs.name }}
          path: ${{ env.artifact_path }}

      - name: deploy
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo "Deploy ......"
          ls -R ${{ env.artifact_path }}
