# Author: Kang Lin<kl222@126.com>

name: build

env:
  artifact_path: artifact_path
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RabbitCommon_VERSION: v2.3.3
  RabbitCommon_VERSION_PRE: v2.3.2

on:
  push:
  pull_request:

jobs:
  ubuntu:
    uses: ./.github/workflows/ubuntu.yml

  msvc:
    uses: ./.github/workflows/msvc.yml

  mingw:
    uses: ./.github/workflows/mingw.yml

  macos:
    uses: ./.github/workflows/macos.yml

  android:
    uses: ./.github/workflows/android.yml

  doxygen:
    uses: ./.github/workflows/doxygen.yml
    if: ${{ startsWith(github.ref, 'refs/tags/') }}

  deploy:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    needs: [ubuntu, msvc, macos, android, doxygen]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Download ubuntu
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.ubuntu.outputs.name }}
          path: ${{ env.artifact_path }}
          merge-multiple: true

      - name: Download msvc
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ needs.msvc.outputs.name }}_*
          path: ${{ env.artifact_path }}
          merge-multiple: true

      - name: Download mingw
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.mingw.outputs.name }}
          path: ${{ env.artifact_path }}
          merge-multiple: true

      - name: Download macos
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ needs.macos.outputs.name }}_*
          path: ${{ env.artifact_path }}
          merge-multiple: true

      - name: Download android
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ needs.android.outputs.name }}_*
          path: ${{ env.artifact_path }}
          merge-multiple: true

      - name: Download doxygen
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.doxygen.outputs.name }}
          path: ${{ env.artifact_path }}
          merge-multiple: true

      - name: Make Note.md file
        run: |
          cd ${{ env.artifact_path }}
          echo "[:cn: 修改日志](https://github.com/KangLin/RabbitCommon/blob/${{env.RabbitCommon_VERSION}}/ChangeLog_zh_CN.md)" > ${{github.workspace}}/Note.md
          echo "[:us: Change log](https://github.com/KangLin/RabbitCommon/blob/${{env.RabbitCommon_VERSION}}/ChangeLog.md)" >> ${{github.workspace}}/Note.md
          echo "" >> ${{github.workspace}}/Note.md
          echo "Full Changelog: [${{env.RabbitCommon_VERSION_PRE}}...${{env.RabbitCommon_VERSION}}](https://github.com/KangLin/RabbitCommon/compare/${{env.RabbitCommon_VERSION_PRE}}...${{env.RabbitCommon_VERSION}})" >> ${{github.workspace}}/Note.md
          echo "" >> ${{github.workspace}}/Note.md
          echo "File checksum:" >> ${{github.workspace}}/Note.md
          echo "|File|Checksum(md5)|" >> ${{github.workspace}}/Note.md
          echo "| :- |    :-       |" >> ${{github.workspace}}/Note.md
          for file in *
          do
              echo "$file"
              if [ -f $file ]; then
                  if [ "${file##*.}" != "xml" ] && [ "${file##*.}" != "json" ]; then
                      md5sum $file > $file.md5sum
                      awk '{print  "|", $2, "|", $1, "|"}' ${file}.md5sum >> ${{github.workspace}}/Note.md
                  fi
              else
                 rm -fr $file
              fi
          done

      - name: Upload To Github Release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          gh release create ${{ github.ref_name }} --title ${{ github.ref_name }} --notes-file ${{github.workspace}}/Note.md
          gh release upload ${{ github.ref_name }} ${{github.workspace}}/${{ env.artifact_path }}/* ${{github.workspace}}/Note.md
