name: CMake mingw

on: [push]

jobs:
  build:
    name: build

    strategy:
      matrix:
        os: [windows-latest]
        # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
        BUILD_TYPE: [Release, Debug]

    defaults:
      run:
        shell: cmd
        
    runs-on: ${{ matrix.os }}
    env:
      BUILD_TYPE:  ${{ matrix.BUILD_TYPE }}
      SOURCE_DIR:  ${{github.workspace}}/source
      TOOSL_DIR:   ${{github.workspace}}/tools
      INSTALL_DIR: ${{github.workspace}}/install

    steps:
    - uses: actions/checkout@v2
      #with:
        #fetch-depth: 0

#    - uses: msys2/setup-msys2@v2
#      with:
#        msystem: MINGW64
#        update: true
#        path-type: strict
#        install: >-
#            mingw-w64-x86_64-cmake
#            mingw-w64-x86_64-nsis
#            mingw-w64-x86_64-make
#            mingw-w64-x86_64-gcc
#            mingw-w64-x86_64-qt5
#            mingw-w64-x86_64-zlib
#            mingw-w64-x86_64-libvncserver
#            mingw-w64-x86_64-cyrus-sasl
#            mingw-w64-x86_64-pixman
#            mingw-w64-x86_64-openjpeg
            
    - name: pacman
      env:
        PATH: C:\msys64\usr\bin
      run: | 
        C:\msys64\usr\bin\pacman.exe -S --noconfirm mingw-w64-x86_64-cmake
        C:\msys64\usr\bin\pacman -S --noconfirm mingw-w64-x86_64-nsis
        C:\msys64\usr\bin\pacman -S --noconfirm mingw-w64-x86_64-make
        C:\msys64\usr\bin\pacman -S --noconfirm mingw-w64-x86_64-gcc
        C:\msys64\usr\bin\pacman -S --noconfirm mingw-w64-x86_64-qt5
        C:\msys64\usr\bin\pacman -S --noconfirm mingw-w64-x86_64-zlib
        C:\msys64\usr\bin\pacman -S --noconfirm git base-devel

    - name: make_directory
      run: |
        cmake -E make_directory ${{env.SOURCE_DIR}}
        cmake -E make_directory ${{env.TOOSL_DIR}}
        cmake -E make_directory ${{env.INSTALL_DIR}}

    - name: build log4qt
      working-directory: ${{env.SOURCE_DIR}}
      env:
        MSYSTEM: MINGW64
        PATH: C:\msys64\mingw64\bin;C:\msys64\usr\bin
      run: |
        git clone -b v1.5.1 "https://github.com/MEONMedical/Log4Qt.git"
        cd Log4Qt
        cmake -E make_directory build
        cd build
        cmake .. -G"MinGW Makefiles" -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{env.INSTALL_DIR}}
        cmake --build . --config ${{matrix.BUILD_TYPE}}
        cmake --build . --config ${{matrix.BUILD_TYPE}} --target install

    - name: build RabbitCommon
      working-directory: ${{github.workspace}}
      env:
        MSYSTEM: MINGW64
        PATH: C:\msys64\mingw64\bin;C:\msys64\usr\bin
      run: |
        cmake -E make_directory build
        cd build
        cmake .. -G"MinGW Makefiles" -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }} -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/build/install -DCMAKE_PREFIX_PATH=${{env.INSTALL_DIR}}/lib/cmake -DLog4Qt_DIR=/lib/cmake/Log4Qt
        cmake --build . --config ${{ matrix.BUILD_TYPE }}
        cmake --build . --config ${{ matrix.BUILD_TYPE }} --target install
