name: CMake ubuntu

on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  build:
    strategy:
      matrix:
        os: [Ubuntu-20.04, Ubuntu-18.04]
        # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
        BUILD_TYPE: [Release, Debug]

    runs-on: ${{ matrix.os }}
    env:
      BUILD_TYPE:  ${{ matrix.BUILD_TYPE }}
      SOURCE_DIR:  ${{github.workspace}}/.cache/source
      TOOSL_DIR:   ${{github.workspace}}/.cache/tools
      INSTALL_DIR: ${{github.workspace}}/.cache/install_ubuntu
      RabbitCommon_VERSION: 1.0.6

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: make_directory
      run: |
        cmake -E make_directory ${{env.SOURCE_DIR}}
        cmake -E make_directory ${{env.TOOSL_DIR}}
        cmake -E make_directory ${{env.INSTALL_DIR}}

    - name: apt helper action
      uses: ryankurte/action-apt@v0.2.0
      with:
        # architectures to pass to dpkg --add-architecture
        #architectures: # optional
        # apt packages to install
        packages: |
            cmake build-essential xvfb xpra libglu1-mesa-dev libpulse-mainloop-glib0 liblog4cxx-dev debhelper dh-systemd fakeroot doxygen qttools5-dev qttools5-dev-tools qtbase5-dev qtbase5-dev-tools qtmultimedia5-dev qtlocation5-dev libqt5svg5-dev qtpositioning5-dev qtwebengine5-dev
    
    - name: build_debpackage.sh
      working-directory: ${{github.workspace}}
      env:
        RabbitCommon_DIR: ${{env.SOURCE_DIR}}/RabbitCommon
        THIRD_LIBRARY_PATH: ${{env.INSTALL_DIR}}
      run: |
        ./build_debpackage.sh /usr/lib/`uname -m`-linux-gnu/qt5
        cp ../rabbitcommon_${{env.RabbitCommon_VERSION}}_amd64.deb rabbitcommon_${{env.RabbitCommon_VERSION}}_amd64_${{ matrix.os }}.deb
        sudo dpkg -i rabbitcommon_${{env.RabbitCommon_VERSION}}_amd64_${{ matrix.os }}.deb
        sudo Xvfb :999 -ac &
        export DISPLAY=:999.0

    - name: update 
      uses: actions/upload-artifact@v2
      with:
          name: rabbitcommon_${{ matrix.os }}
          path: |
            rabbitcommon_${{env.RabbitCommon_VERSION}}_amd64_${{ matrix.os }}.deb
            update_linux.xml
      if: ${{ matrix.BUILD_TYPE == 'Release' }} 

    - name: Upload To Github Release
      if: ${{ matrix.BUILD_TYPE == 'Release' && startsWith(github.ref, 'refs/tags/') }}
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        prerelease: true
        body: |
           [:cn: 修改日志](ChangeLog_zh_CN.md) [:us: Change log](ChangeLog.md)
        files: |
            ${{github.workspace}}/rabbitcommon_${{env.RabbitCommon_VERSION}}_amd64_${{ matrix.os }}.deb
            update_linux.xml
